{
    'name': 'MHMA Invetory',
    'version': '1.0',
    'summary': '',
    'author': 'MHMA',
    'category': 'Inventory',
    'depends': [
        'base',
        'stock', 
        'stock_landed_costs', 
        'stock_landed_costs_company', 
        'stock_account', 
        'sale_stock', 
        'purchase_stock', 
        'stock_delivery', 
        'purchase_requisition_stock', 
        'mhma_stock_no_negative', 
        'mhma_stock_picking_import', 
        'product_expiry',
        'product', 
        'hr', 
        'approvals', 
        'purchase', 
        'mail', 
        'repair',
        'hr_expense',
        'mhma_purchase',
        ],
    'data': [
        "security/security.xml",
        "security/ir.model.access.csv",
        "security/inventory_readonly/ir.model.access.csv",
        "security/purchase_readonly/ir.model.access.csv",
        "security/purchase_inventory_manager/ir.model.access.csv",
        "security/purchase_inventory_manager/security.xml",
        "security/purchase_officer/ir.model.access.csv",
        "security/purchase_officer/security.xml",
        "security/purchase_inventory_accountant/ir.model.access.csv",
        "security/stock_keeper/ir.model.access.csv",
        'data/portrait_custom_paperformat.xml',
        'report/external_layout_custom.xml',
        'views/demand_product.xml',
        'views/demand_product_line.xml',
        'report/stock_picking_report.xml',
        'report/report_approval_request.xml', 
        'report/stock_delivery.xml',
        'report/rfq_mhma_report.xml',
        'views/res_partner.xml',
        'views/stock_picking.xml',
        'views/product_template.xml',
        'views/stock_move_line.xml',
        'views/stock_valuation_layer.xml',
        'views/approval_category.xml',
        'views/approval_request.xml',
        'views/purchase_order.xml',
        'views/stock_move_valuation.xml',
        'views/product_category.xml',
        'views/combo_products.xml',
        'views/hr_expense.xml',
        'views/menu.xml',
        'views/menu_approval.xml',
        'wizards/approval_rejection_reason.xml',
        'wizards/inventory_ledger_summary_wizard.xml',
        'wizards/inventory_ledger_summary_wizard_line.xml',
        'views/menu/purchase_readonly_menu_inherit.xml',
        'views/menu/inventory_readonly_menu_inherit.xml',

    ],
    'installable': True,
    'application': False,
    'license': 'LGPL-3',
}
